{% set name = "pynhd" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: f3c2b70e6b337554cb44d4a718082c4ec900576a1db6987436062867eb58aa77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - async-retriever <0.19,>=0.18
    - cytoolz
    - geopandas-base >=1
    - pyogrio
    - networkx
    - numpy >=2
    - pandas >=1.0
    - pyarrow >=1.0.1
    - pygeoogc <0.19,>=0.18
    - pygeoutils <0.19,>=0.18
    - shapely >=2

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pynhd
  summary: Access and navigate NHDPlus V2 via various web services, e.g., NLDI and WaterData.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
