{% set name = "pynhd" %}
{% set version = "0.19.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pynhd-{{ version }}.tar.gz
  sha256: 1cac07e2522d8839af8edf72198c9cf051c8cdaf18b02fdafc94dcbf87d9651d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - async-retriever >=0.19.3,<0.20
    - cytoolz
    - geopandas-base >=1
    - pyogrio
    - networkx
    - numpy >=2
    - pandas >=1.0
    - pyarrow >=1.0.1
    - pygeoogc >=0.19.3,<0.20
    - pygeoutils >=0.19.5,<0.20
    - shapely >=2

test:
  imports:
    - pynhd
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hyriver/pynhd
  summary: Access and navigate NHDPlus V2 via various web services, e.g., NLDI and WaterData.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
